// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: msg/generic.proto

package msg

import (
	chain "github.com/adithyabhatkajake/libsynchs/chain"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SyncHSMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*SyncHSMsg_Prop
	//	*SyncHSMsg_Npblame
	//	*SyncHSMsg_Eqblame
	//	*SyncHSMsg_Ack
	//	*SyncHSMsg_Cmd
	//	*SyncHSMsg_QV
	//	*SyncHSMsg_Vote
	Msg isSyncHSMsg_Msg `protobuf_oneof:"Msg"`
}

func (x *SyncHSMsg) Reset() {
	*x = SyncHSMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_generic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncHSMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHSMsg) ProtoMessage() {}

func (x *SyncHSMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_generic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHSMsg.ProtoReflect.Descriptor instead.
func (*SyncHSMsg) Descriptor() ([]byte, []int) {
	return file_msg_generic_proto_rawDescGZIP(), []int{0}
}

func (m *SyncHSMsg) GetMsg() isSyncHSMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SyncHSMsg) GetProp() *Proposal {
	if x, ok := x.GetMsg().(*SyncHSMsg_Prop); ok {
		return x.Prop
	}
	return nil
}

func (x *SyncHSMsg) GetNpblame() *NoProgressBlame {
	if x, ok := x.GetMsg().(*SyncHSMsg_Npblame); ok {
		return x.Npblame
	}
	return nil
}

func (x *SyncHSMsg) GetEqblame() *EquivocationBlame {
	if x, ok := x.GetMsg().(*SyncHSMsg_Eqblame); ok {
		return x.Eqblame
	}
	return nil
}

func (x *SyncHSMsg) GetAck() *CommitAck {
	if x, ok := x.GetMsg().(*SyncHSMsg_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *SyncHSMsg) GetCmd() *chain.Command {
	if x, ok := x.GetMsg().(*SyncHSMsg_Cmd); ok {
		return x.Cmd
	}
	return nil
}

func (x *SyncHSMsg) GetQV() *QuitView {
	if x, ok := x.GetMsg().(*SyncHSMsg_QV); ok {
		return x.QV
	}
	return nil
}

func (x *SyncHSMsg) GetVote() *Vote {
	if x, ok := x.GetMsg().(*SyncHSMsg_Vote); ok {
		return x.Vote
	}
	return nil
}

type isSyncHSMsg_Msg interface {
	isSyncHSMsg_Msg()
}

type SyncHSMsg_Prop struct {
	Prop *Proposal `protobuf:"bytes,1,opt,name=Prop,proto3,oneof"`
}

type SyncHSMsg_Npblame struct {
	Npblame *NoProgressBlame `protobuf:"bytes,2,opt,name=Npblame,proto3,oneof"`
}

type SyncHSMsg_Eqblame struct {
	Eqblame *EquivocationBlame `protobuf:"bytes,3,opt,name=Eqblame,proto3,oneof"`
}

type SyncHSMsg_Ack struct {
	Ack *CommitAck `protobuf:"bytes,4,opt,name=Ack,proto3,oneof"`
}

type SyncHSMsg_Cmd struct {
	Cmd *chain.Command `protobuf:"bytes,5,opt,name=Cmd,proto3,oneof"`
}

type SyncHSMsg_QV struct {
	QV *QuitView `protobuf:"bytes,6,opt,name=QV,proto3,oneof"`
}

type SyncHSMsg_Vote struct {
	Vote *Vote `protobuf:"bytes,7,opt,name=Vote,proto3,oneof"`
}

func (*SyncHSMsg_Prop) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_Npblame) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_Eqblame) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_Ack) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_Cmd) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_QV) isSyncHSMsg_Msg() {}

func (*SyncHSMsg_Vote) isSyncHSMsg_Msg() {}

var File_msg_generic_proto protoreflect.FileDescriptor

var file_msg_generic_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x12, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6d, 0x73,
	0x67, 0x2f, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d,
	0x73, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63,
	0x48, 0x53, 0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x4e, 0x70,
	0x62, 0x6c, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4e, 0x6f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6c, 0x61, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x4e, 0x70, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x07,
	0x45, 0x71, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x6c, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x45, 0x71, 0x62, 0x6c, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x03, 0x41, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x48, 0x00, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x1f, 0x0a, 0x02, 0x51, 0x56, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x48, 0x00, 0x52, 0x02, 0x51, 0x56, 0x12, 0x1f, 0x0a, 0x04, 0x56, 0x6f, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x48, 0x00, 0x52, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x64, 0x69, 0x74, 0x68, 0x79, 0x61, 0x62, 0x68, 0x61, 0x74, 0x6b, 0x61, 0x6a, 0x61, 0x6b,
	0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_generic_proto_rawDescOnce sync.Once
	file_msg_generic_proto_rawDescData = file_msg_generic_proto_rawDesc
)

func file_msg_generic_proto_rawDescGZIP() []byte {
	file_msg_generic_proto_rawDescOnce.Do(func() {
		file_msg_generic_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_generic_proto_rawDescData)
	})
	return file_msg_generic_proto_rawDescData
}

var file_msg_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msg_generic_proto_goTypes = []interface{}{
	(*SyncHSMsg)(nil),         // 0: msg.SyncHSMsg
	(*Proposal)(nil),          // 1: msg.Proposal
	(*NoProgressBlame)(nil),   // 2: msg.NoProgressBlame
	(*EquivocationBlame)(nil), // 3: msg.EquivocationBlame
	(*CommitAck)(nil),         // 4: msg.CommitAck
	(*chain.Command)(nil),     // 5: chain.Command
	(*QuitView)(nil),          // 6: msg.QuitView
	(*Vote)(nil),              // 7: msg.Vote
}
var file_msg_generic_proto_depIdxs = []int32{
	1, // 0: msg.SyncHSMsg.Prop:type_name -> msg.Proposal
	2, // 1: msg.SyncHSMsg.Npblame:type_name -> msg.NoProgressBlame
	3, // 2: msg.SyncHSMsg.Eqblame:type_name -> msg.EquivocationBlame
	4, // 3: msg.SyncHSMsg.Ack:type_name -> msg.CommitAck
	5, // 4: msg.SyncHSMsg.Cmd:type_name -> chain.Command
	6, // 5: msg.SyncHSMsg.QV:type_name -> msg.QuitView
	7, // 6: msg.SyncHSMsg.Vote:type_name -> msg.Vote
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_msg_generic_proto_init() }
func file_msg_generic_proto_init() {
	if File_msg_generic_proto != nil {
		return
	}
	file_msg_proposal_proto_init()
	file_msg_blame_proto_init()
	file_msg_clientAck_proto_init()
	file_msg_vote_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_generic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncHSMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_generic_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SyncHSMsg_Prop)(nil),
		(*SyncHSMsg_Npblame)(nil),
		(*SyncHSMsg_Eqblame)(nil),
		(*SyncHSMsg_Ack)(nil),
		(*SyncHSMsg_Cmd)(nil),
		(*SyncHSMsg_QV)(nil),
		(*SyncHSMsg_Vote)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_generic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_generic_proto_goTypes,
		DependencyIndexes: file_msg_generic_proto_depIdxs,
		MessageInfos:      file_msg_generic_proto_msgTypes,
	}.Build()
	File_msg_generic_proto = out.File
	file_msg_generic_proto_rawDesc = nil
	file_msg_generic_proto_goTypes = nil
	file_msg_generic_proto_depIdxs = nil
}
