// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: msg/vote.proto

package msg

import (
	chain "github.com/adithyabhatkajake/libsynchs/chain"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      *VoteData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Origin    uint64    `protobuf:"varint,2,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Signature []byte    `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *Vote) Reset() {
	*x = Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_vote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_msg_vote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_msg_vote_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetData() *VoteData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Vote) GetOrigin() uint64 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *Vote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VoteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *chain.Block `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"` // Bk
	View  uint64       `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`  // v
}

func (x *VoteData) Reset() {
	*x = VoteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_vote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteData) ProtoMessage() {}

func (x *VoteData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_vote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteData.ProtoReflect.Descriptor instead.
func (*VoteData) Descriptor() ([]byte, []int) {
	return file_msg_vote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteData) GetBlock() *chain.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *VoteData) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

type BlockCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BCert *Certificate `protobuf:"bytes,1,opt,name=BCert,proto3" json:"BCert,omitempty"`
	Data  *VoteData    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *BlockCertificate) Reset() {
	*x = BlockCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_vote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCertificate) ProtoMessage() {}

func (x *BlockCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_msg_vote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCertificate.ProtoReflect.Descriptor instead.
func (*BlockCertificate) Descriptor() ([]byte, []int) {
	return file_msg_vote_proto_rawDescGZIP(), []int{2}
}

func (x *BlockCertificate) GetBCert() *Certificate {
	if x != nil {
		return x.BCert
	}
	return nil
}

func (x *BlockCertificate) GetData() *VoteData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_msg_vote_proto protoreflect.FileDescriptor

var file_msg_vote_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x11, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x65,
	0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x42, 0x0a, 0x08, 0x56, 0x6f, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65,
	0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x22, 0x5d, 0x0a,
	0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x42, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x42, 0x43, 0x65, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x69, 0x74, 0x68,
	0x79, 0x61, 0x62, 0x68, 0x61, 0x74, 0x6b, 0x61, 0x6a, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x62,
	0x73, 0x79, 0x6e, 0x63, 0x68, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_msg_vote_proto_rawDescOnce sync.Once
	file_msg_vote_proto_rawDescData = file_msg_vote_proto_rawDesc
)

func file_msg_vote_proto_rawDescGZIP() []byte {
	file_msg_vote_proto_rawDescOnce.Do(func() {
		file_msg_vote_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_vote_proto_rawDescData)
	})
	return file_msg_vote_proto_rawDescData
}

var file_msg_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msg_vote_proto_goTypes = []interface{}{
	(*Vote)(nil),             // 0: msg.Vote
	(*VoteData)(nil),         // 1: msg.VoteData
	(*BlockCertificate)(nil), // 2: msg.BlockCertificate
	(*chain.Block)(nil),      // 3: chain.Block
	(*Certificate)(nil),      // 4: msg.Certificate
}
var file_msg_vote_proto_depIdxs = []int32{
	1, // 0: msg.Vote.Data:type_name -> msg.VoteData
	3, // 1: msg.VoteData.Block:type_name -> chain.Block
	4, // 2: msg.BlockCertificate.BCert:type_name -> msg.Certificate
	1, // 3: msg.BlockCertificate.Data:type_name -> msg.VoteData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msg_vote_proto_init() }
func file_msg_vote_proto_init() {
	if File_msg_vote_proto != nil {
		return
	}
	file_msg_cert_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_vote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_vote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_vote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_vote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_vote_proto_goTypes,
		DependencyIndexes: file_msg_vote_proto_depIdxs,
		MessageInfos:      file_msg_vote_proto_msgTypes,
	}.Build()
	File_msg_vote_proto = out.File
	file_msg_vote_proto_rawDesc = nil
	file_msg_vote_proto_goTypes = nil
	file_msg_vote_proto_depIdxs = nil
}
